// ============================================================================
// === FIGHTERS ===============================================================
// Roster definitions. Each fighter has stats, visual identity, ability id,
// and card metadata. Edit here to tune balance numbers.
// ============================================================================

const FIGHTERS = [
  { id:'priest',  name:'PRIEST',    hp:80,  speed:110, size:16, color:'#f5f5f0', accent:'#ffe83d', shape:'cross',  ability:'lightning', cd:1.4, dmg:18, rotates:true, active:'LIGHTNING BOLT — homing zap, 0.45s windup',     passive:'DIVINE GRACE — heal 1.0 hp/s' },
  { id:'berserker',name:'BERSERKER', hp:105, speed:145, size:18, color:'#a83232', accent:'#f5f5f0', shape:'axe',    ability:'tackle',    cd:1.7, dmg:18, rotates:true,  active:'TACKLE DASH — charge that hits on collision',     passive:'BLOODRAGE — +30% speed under 50% hp' },
  { id:'wizard',  name:'WIZARD',    hp:66,  speed:95,  size:16, color:'#9d4edd', accent:'#ffe83d', shape:'spellbook',   ability:'cast',    cd:2.5, dmg:11,  rotates:true, active:'CAST ORBS — 2 homing orbs per cast, max 4',       passive:'MANA SHIELD — 50% dmg reduction, spends an orb per hit' },
  { id:'knight',  name:'KNIGHT',    hp:105, speed:90,  size:18, color:'#c0c0c0', accent:'#2e9eff', shape:'shield', ability:'sword',     cd:1.2, dmg:20, strikeReach:12, rotates:true,  active:'SWORD LUNGE — dash in and strike on reach',       passive:'PLATE ARMOR — −2 dmg per hit (min 1)' },
  { id:'sapper', name:'SAPPER',    hp:70,  speed:120, size:16, color:'#5a3a1f', accent:'#ff2e2e', shape:'keg',    ability:'mine',      cd:1.4, dmg:28, rotates:true, active:'DROP MINE — proximity trap, arms after 0.5s',     passive:'WAKE — soot trail slows enemies by 40%' },
  { id:'archer',  name:'ARCHER',    hp:75,  speed:130, size:16, color:'#3dff8a', accent:'#f5f5f0', shape:'bow',    ability:'arrow',     cd:0.9, dmg:7,  rotates:true,  active:'RAPID ARROWS — fires while moving, no windup',    passive:'VOLLEY — every 4th shot fans 4 arrows' },
  { id:'jester',  name:'JESTER',    hp:73,  speed:120, size:16, color:'#e8d8b8', accent:'#ff2e2e', shape:'mask',   ability:'blink',     cd:2.5, dmg:13, rotates:true, active:'BLINK DAGGER — teleports behind enemy and stabs',   passive:'UNCANNY DODGE — phases through next hit, 6.0s cd' },
  { id:'cannoneer',name:'CANNONEER',hp:103, speed:85,  size:18, color:'#4a4a4a', accent:'#ff8c1a', shape:'cannon', ability:'cannon',    cd:3.0, dmg:31, rotates:true,  active:'CANNON SHOT — 1.0s windup, fast straight shot',     passive:'INCENDIARY ROUND — cannon hits leave a brief burning impact zone' },
  { id:'duelist', name:'DUELIST',   hp:93,  speed:115, size:16, color:'#1a1a2e', accent:'#c0c0e8', shape:'rapier', ability:'riposte',   cd:1.7, dmg:26, strikeReach:10, rotates:true,  active:'RIPOSTE THRUST — dash in and thrust on reach, reflects projectiles', passive:'COUNTER — melee hits trigger an automatic counter-thrust' },
  { id:'necromancer',name:'NECROMANCER',hp:95, speed:100, size:16, color:'#3a2a4a', accent:'#e8e0d0', shape:'scythe', ability:'raise',  cd:2.9, dmg:8,  rotates:true,  active:'RAISE SKELETON — summons a slow skeleton, no cap',   passive:'BONE BURST — skeletons explode on death, damaging nearby foes' },
  { id:'reaper',  name:'REAPER',    hp:106, speed:100, size:16, color:'#1a0e0e', accent:'#aa0000', shape:'sickles',ability:'sweep',  cd:1.0,dmg:16, strikeReach:14, rotates:true,  active:'WHIRLING BLADES — dash in and 360° spin on reach',    passive:'BLOOD HARVEST — heal 50% of damage dealt' },
  { id:'ronin',   name:'RONIN',     hp:81,  speed:100, size:16, color:'#2a1a1a', accent:'#e8c020', shape:'katana', ability:'iai',    cd:2.8, dmg:35, rotates:true,  active:'IAI SLASH — 0.7s windup, then dashing heavy strike', passive:'IAIJUTSU — hitting with iai halves the cooldown' },
  { id:'witch',   name:'WITCH',     hp:73,  speed:100, size:16, color:'#2d4a2a', accent:'#7dff3d', shape:'hat',  ability:'hex',    cd:1.5, dmg:11, rotates:true,  active:'HEX BOLT — bouncing projectile, up to 5 wall bounces', passive:'WITCH\'S MARK — marked enemies take +50% damage for 3s' },
  { id:'hunter',  name:'HUNTER',    hp:84,  speed:115, size:16, color:'#3a2818', accent:'#c89060', shape:'hook',   ability:'grapple', cd:1.5, dmg:18, rotates:true,  active:'GRAPPLING HOOK — fires a hook that wounds and reels the enemy in',  passive:'CRIPPLING HOOK — a hooked enemy is briefly stunned' },
  { id:'warlock', name:'WARLOCK',   hp:57,  speed:100, size:16, color:'#2a0e2e', accent:'#c050ff', shape:'cowl',   ability:'drain',  cd:2.2, dmg:4,  rotates:true,  active:'DRAIN BEAM — channels a beam that drains the enemy\'s HP', passive:'ENERVATE — tethered enemies move at 60% speed, drain heals 35%' },
  { id:'gambler', name:'GAMBLER',   hp:91,  speed:110, size:16, color:'#1a3a2a', accent:'#ffd23d', shape:'dice',   ability:'wildcard',cd:1.5,dmg:5, rotates:true,  active:'WILDCARD — roll a die; higher pips, bigger coin attack',     passive:'LOADED DICE — a low roll halves the next cooldown' },
];
