// ============================================================================
// === FIGHTERS ===============================================================
// Roster definitions. Each fighter has stats, visual identity, ability id,
// and card metadata. Edit here to tune balance numbers.
//
// Ability parameters (windupTime, healRate, etc.) are defined as named
// properties on the fighter object — the single source of truth. Description
// strings are getters that read those properties, so they can never drift.
// Ability code reads f.propertyName instead of hardcoded literals.
// ============================================================================

const FIGHTER_SIZE = 16;

const FIGHTERS = [
  { id:'priest',  name:'PRIEST',    hp:80,  speed:110, color:'#f5f5f0', accent:'#ffe83d', shape:'cross',
    ability:'lightning', cd:1.4, dmg:18,
    windupTime: 0.45, healRate: 1.0,
    get active() { return `LIGHTNING BOLT — homing zap, ${this.windupTime}s windup`; },
    get passive() { return `DIVINE GRACE — heal ${this.healRate} hp/s`; },
  },
  { id:'berserker',name:'BERSERKER', hp:105, speed:145, color:'#a83232', accent:'#f5f5f0', shape:'axe',
    ability:'tackle', cd:1.7, dmg:18,
    rageBoost: 0.33,
    active: 'TACKLE DASH — charge that hits on collision',
    get passive() { return `BLOODRAGE — +${Math.round(this.rageBoost * 100)}% speed under 50% hp`; },
  },
  { id:'wizard',  name:'WIZARD',    hp:70,  speed:95,  color:'#9d4edd', accent:'#ffe83d', shape:'spellbook',
    ability:'cast', cd:2.0, dmg:10,
    orbsPerCast: 2, orbCap: 4, shieldReduction: 0.20,
    get active() { return `CAST ORBS — ${this.orbsPerCast} homing orbs per cast, max ${this.orbCap}`; },
    get passive() { return `MANA SHIELD — ${Math.round(this.shieldReduction * 100)}% dmg reduction per orb (up to ${Math.round(this.orbCap * this.shieldReduction * 100)}%), spends one orb per hit`; },
  },
  { id:'knight',  name:'KNIGHT',    hp:111, speed:90,  color:'#c0c0c0', accent:'#2e9eff', shape:'shield',
    ability:'sword', cd:1.2, dmg:20, strikeReach:12,
    armorFlat: 2,
    active: 'SHIELD BASH — dash in and slam on reach',
    get passive() { return `PLATE ARMOR — −${this.armorFlat} dmg per hit (min 1)`; },
  },
  { id:'sapper', name:'SAPPER',    hp:72,  speed:120, color:'#5a3a1f', accent:'#ff2e2e', shape:'keg',
    ability:'mine', cd:1.4, dmg:28,
    mineArmDelay: 0.5,
    get active() { return `DROP MINE — proximity trap, arms after ${this.mineArmDelay}s`; },
    passive: 'BLAST RADIUS — mine explosions knock enemies back',
  },
  { id:'archer',  name:'ARCHER',    hp:73,  speed:125, color:'#3dff8a', accent:'#f5f5f0', shape:'bow',
    ability:'arrow', cd:0.9, dmg:7,
    volleyEvery: 4, volleyCount: 4,
    active: 'RAPID ARROWS — fires while moving, no windup',
    get passive() { return `VOLLEY — every ${this.volleyEvery}th shot fans ${this.volleyCount} arrows`; },
  },
  { id:'jester',  name:'JESTER',    hp:75,  speed:120, color:'#e8d8b8', accent:'#ff2e2e', shape:'mask',
    ability:'blink', cd:2.5, dmg:13,
    dodgeCd: 6.0,
    active: 'BLINK DAGGER — teleports behind enemy and stabs',
    get passive() { return `UNCANNY DODGE — phases through next hit, ${this.dodgeCd}s cd`; },
  },
  { id:'cannoneer',name:'CANNONEER',hp:103, speed:85,  color:'#4a4a4a', accent:'#ff8c1a', shape:'cannon',
    ability:'cannon', cd:3.0, dmg:30,
    windupTime: 1.0,
    get active() { return `CANNON SHOT — ${this.windupTime}s windup, fast straight shot`; },
    passive: 'INCENDIARY ROUND — cannon hits leave a brief burning impact zone',
  },
  { id:'duelist', name:'DUELIST',   hp:95,  speed:115, color:'#1a1a2e', accent:'#c0c0e8', shape:'rapier',
    ability:'riposte', cd:1.7, dmg:25, strikeReach:10,
    active: 'RIPOSTE THRUST — dash in and thrust on reach, reflects projectiles',
    passive: 'COUNTER — melee hits trigger an automatic counter-thrust',
  },
  { id:'necromancer',name:'NECROMANCER',hp:95, speed:100, color:'#3a2a4a', accent:'#e8e0d0', shape:'scythe',
    ability:'raise', cd:2.9, dmg:6,
    active: 'RAISE SKELETON — summons a slow skeleton, no cap',
    passive: 'BONE BURST — skeletons explode on death, damaging nearby foes',
  },
  { id:'reaper',  name:'REAPER',    hp:110, speed:100, color:'#1a0e0e', accent:'#aa0000', shape:'sickles',
    ability:'sweep', cd:1.0, dmg:16, strikeReach:14,
    harvestRate: 0.5,
    active: 'WHIRLING BLADES — dash in and 360° spin on reach',
    get passive() { return `BLOOD HARVEST — heal ${Math.round(this.harvestRate * 100)}% of damage dealt`; },
  },
  { id:'ronin',   name:'RONIN',     hp:92,  speed:100, color:'#2a1a1a', accent:'#e8c020', shape:'katana',
    ability:'iai', cd:3.6, dmg:35,
    windupTime: 0.7,
    get active() { return `IAI SLASH — ${this.windupTime}s windup, then dashing heavy strike`; },
    passive: 'IAIJUTSU — hitting with iai halves the cooldown',
  },
  { id:'witch',   name:'WITCH',     hp:78,  speed:100, color:'#2d4a2a', accent:'#7dff3d', shape:'hat',
    ability:'hex', cd:1.5, dmg:11,
    maxBounces: 5, markBonus: 0.5, markDuration: 3.0,
    get active() { return `HEX BOLT — bouncing projectile, up to ${this.maxBounces} wall bounces`; },
    get passive() { return `WITCH'S MARK — marked enemies take +${Math.round(this.markBonus * 100)}% damage for ${this.markDuration}s`; },
  },
  { id:'hunter',  name:'HUNTER',    hp:81,  speed:110, color:'#3a2818', accent:'#c89060', shape:'hook',
    ability:'grapple', cd:1.5, dmg:18,
    active: 'GRAPPLING HOOK — fires a hook that wounds and reels the enemy in',
    passive: 'CRIPPLING HOOK — a hooked enemy is briefly stunned',
  },
  { id:'warlock', name:'WARLOCK',   hp:57,  speed:100, color:'#2a0e2e', accent:'#c050ff', shape:'cowl',
    ability:'drain', cd:2.2, dmg:4,
    slowRate: 0.6, drainHealRate: 0.35,
    active: 'DRAIN BEAM — channels a beam that drains the enemy\'s HP',
    get passive() { return `ENERVATE — tethered enemies move at ${Math.round(this.slowRate * 100)}% speed, drain heals ${Math.round(this.drainHealRate * 100)}%`; },
  },
  { id:'gambler', name:'GAMBLER',   hp:91,  speed:100, color:'#1a3a2a', accent:'#ffd23d', shape:'dice',
    ability:'wildcard', cd:1.5, dmg:5,
    active: 'WILDCARD — roll a die; higher pips, bigger coin attack',
    passive: 'LOADED DICE — a low roll halves the next cooldown',
  },
];
