// === VICTORY QUOTES ==========================================================
// Cheesy one-liners keyed 'winner_loser'. showWinnerOverlay() picks the entry
// matching the actual outcome; falls back to '_default_' if missing.
// ============================================================================
const VICTORY_QUOTES = {

  // PRIEST wins
  'priest_berserker':   "Rage is a prayer too. Just not the answered kind.",
  'priest_wizard':      "The light outshines even the brightest spell.",
  'priest_knight':      "Even the armored kneel in the end.",
  'priest_sapper':      "No mine survives a blessing.",
  'priest_archer':      "God's aim is better.",
  'priest_jester':      "The joke was on you. Literally.",
  'priest_cannoneer':   "The heavens have better artillery.",
  'priest_duelist':     "Counter-thrust? Try divine intervention.",
  'priest_necromancer': "The undead fear the divine. As they should.",
  'priest_reaper':      "Even death has a god.",
  'priest_ronin':       "The blade met something sharper: faith.",
  'priest_witch':       "Hex vs. blessing. Blessings win.",
  'priest_hunter':      "You can't hook what heaven holds.",
  'priest_warlock':     "Drain meets an inexhaustible source.",
  'priest_gambler':     "God doesn't gamble. You should've known.",

  // BERSERKER wins
  'berserker_priest':      "Pray faster next time.",
  'berserker_wizard':      "Your orbs bounced. My axe didn't.",
  'berserker_knight':      "More armor, less speed. Wrong trade.",
  'berserker_sapper':      "Mines don't arm that fast.",
  'berserker_archer':      "You backed into the wall.",
  'berserker_jester':      "Blink all you want. I'm everywhere.",
  'berserker_cannoneer':   "No windup. Just up.",
  'berserker_duelist':     "Counter this.",
  'berserker_necromancer': "Your skeleton army needed more skeletons.",
  'berserker_reaper':      "Blood harvest requires blood. Mine isn't for taking.",
  'berserker_ronin':       "Your windup was my opening.",
  'berserker_witch':       "Your hex didn't slow the bloodrage.",
  'berserker_hunter':      "The hook missed. The tackle didn't.",
  'berserker_warlock':     "Can't drain someone who doesn't stop moving.",
  'berserker_gambler':     "No dice needed when you have this much speed.",

  // WIZARD wins
  'wizard_priest':      "The divine light? Absorbed by the mana shield.",
  'wizard_berserker':   "Speed is useless against homing.",
  'wizard_knight':      "Plate armor stops swords. Not orbs.",
  'wizard_sapper':      "Mines need arm time. Orbs don't.",
  'wizard_archer':      "Your arrows were outpaced by my orbs.",
  'wizard_jester':      "Can't blink away from four homing orbs.",
  'wizard_cannoneer':   "Long windup. Short landing.",
  'wizard_duelist':     "Reflect all you want. I have four more.",
  'wizard_necromancer': "Even undead magic bends to the arcane.",
  'wizard_reaper':      "An impossible day. Frame this.",
  'wizard_ronin':       "The slash hit shield. The orbs hit you.",
  'wizard_witch':       "Your hex bounced off my mana shield.",
  'wizard_hunter':      "You can't reel in an orb.",
  'wizard_warlock':     "Drain vs. mana shield. Classic mismatch.",
  'wizard_gambler':     "Luck doesn't beat a stacked deck of orbs.",

  // KNIGHT wins
  'knight_priest':      "God's on your side? I'm on your face.",
  'knight_berserker':   "Faster? Yes. Enough? No.",
  'knight_wizard':      "Plate armor: orb repellent certified.",
  'knight_sapper':      "The mines didn't arm fast enough.",
  'knight_archer':      "You ran out of arena.",
  'knight_jester':      "Blink behind me. I'll turn around.",
  'knight_cannoneer':   "Artillery loses to a charge.",
  'knight_duelist':     "Your riposte was a quarter-second slow.",
  'knight_necromancer': "Skeletons vs. plate armor. No contest.",
  'knight_reaper':      "Every gap in the armor was covered.",
  'knight_ronin':       "The lunge got there first.",
  'knight_witch':       "Your mark wore off before the fight did.",
  'knight_hunter':      "The hook bounced off the plate.",
  'knight_warlock':     "Can't drain through plate armor.",
  'knight_gambler':     "Your dice said no.",

  // SAPPER wins
  'sapper_priest':      "The mine was already armed before the prayer finished.",
  'sapper_berserker':   "Speed gets you nowhere in a minefield.",
  'sapper_wizard':      "Even orbs can't defuse what they can't see.",
  'sapper_knight':      "Classic. Charging into a minefield.",
  'sapper_archer':      "Run into the soot. Run into the mine.",
  'sapper_jester':      "You blinked. Right onto it.",
  'sapper_cannoneer':   "Slow artillery vs. instant proximity fuse.",
  'sapper_duelist':     "Thrust into a mine. Elegant to the end.",
  'sapper_necromancer': "Skeletons triggered the mines. Mines triggered you.",
  'sapper_reaper':      "Your harvest stepped on my field.",
  'sapper_ronin':       "IAI slashes through soot. Soot slows. Mine detonates.",
  'sapper_witch':       "The hex slowed me right into the mine. Oops.",
  'sapper_hunter':      "Your hook pulled me straight over one.",
  'sapper_warlock':     "The drain beam lit up the soot trail perfectly.",
  'sapper_gambler':     "Bad roll. Wrong step.",

  // ARCHER wins
  'archer_priest':      "Lightning needs a target that stays still.",
  'archer_berserker':   "You charged through twenty arrows.",
  'archer_wizard':      "Homing orbs can't catch what's always moving.",
  'archer_knight':      "Plate armor has gaps. Arrows find them.",
  'archer_sapper':      "I ran circles around your minefield.",
  'archer_jester':      "You blinked to my back. I was already shooting.",
  'archer_cannoneer':   "One-second windup. I fired twelve.",
  'archer_duelist':     "Parry all four of the volley. Go on.",
  'archer_necromancer': "Skeletons are slow. Arrows aren't.",
  'archer_reaper':      "Can't harvest what you can never reach.",
  'archer_ronin':       "The windup was my warmup.",
  'archer_witch':       "Your hex bolt ricochets. Arrows go straight.",
  'archer_hunter':      "Two can play the range game. I play it better.",
  'archer_warlock':     "Your beam needs line of sight. I denied it.",
  'archer_gambler':     "No coin beats a full quiver.",

  // JESTER wins
  'jester_priest':      "The blessing couldn't track the blink.",
  'jester_berserker':   "Can't tackle what isn't there.",
  'jester_wizard':      "Behind you. Behind you. Behind you.",
  'jester_knight':      "Lunge at empty air. I'll be back.",
  'jester_sapper':      "The mine couldn't arm. I was already gone.",
  'jester_archer':      "Every arrow landed where I used to be.",
  'jester_cannoneer':   "One shot. Missed. I had twelve blinks.",
  'jester_duelist':     "Counter-thrust into nothing.",
  'jester_necromancer': "Even skeletons can't follow a blink.",
  'jester_reaper':      "Turns out jokes can kill. Who knew.",
  'jester_ronin':       "The iai hit my afterimage. Classic.",
  'jester_witch':       "Marked me. Still couldn't hit me.",
  'jester_hunter':      "Hook landed. On air.",
  'jester_warlock':     "Line of sight. I don't believe in it.",
  'jester_gambler':     "Your dice said no. My dodge said yes.",

  // CANNONEER wins
  'cannoneer_priest':      "Lightning stings. Cannonballs conclude.",
  'cannoneer_berserker':   "Fast enough to dodge the shot? No.",
  'cannoneer_wizard':      "The orbs couldn't reach before the shot did.",
  'cannoneer_knight':      "Plate armor is for swords, not cannonballs.",
  'cannoneer_sapper':      "Your minefield needed a wider radius.",
  'cannoneer_archer':      "Spray and pray vs. one perfect shot. One won.",
  'cannoneer_jester':      "Blink into the impact zone. That's on you.",
  'cannoneer_duelist':     "You reflected it. I fired another.",
  'cannoneer_necromancer': "The skeleton walked straight into the shot.",
  'cannoneer_reaper':      "The blood harvest ran out of blood.",
  'cannoneer_ronin':       "Your windup met my windup. Mine's heavier.",
  'cannoneer_witch':       "Hex bounced off. Cannonball didn't.",
  'cannoneer_hunter':      "The hook pulled you into my line of fire.",
  'cannoneer_warlock':     "You needed time to ramp. I had one shot.",
  'cannoneer_gambler':     "Your dice said snake eyes. Mine said loaded.",

  // DUELIST wins
  'duelist_priest':      "Lightning reflected. You were in the way.",
  'duelist_berserker':   "Counter-thrust on the tackle. Textbook.",
  'duelist_wizard':      "Reflected four orbs. You ran out.",
  'duelist_knight':      "Lunge into a riposte. Classic mistake.",
  'duelist_sapper':      "Thrust through the soot. Didn't slow the blade.",
  'duelist_archer':      "Arrow reflected. The volley reflected. You ran out.",
  'duelist_jester':      "The blink put you right in thrust range.",
  'duelist_cannoneer':   "The cannonball came back at you.",
  'duelist_necromancer': "Counter on the skeleton. Burst on you.",
  'duelist_reaper':      "Whirling blades, counter-thrust. Repeat.",
  'duelist_ronin':       "Faster reach. Didn't need the windup.",
  'duelist_witch':       "The hex landed. The thrust landed first.",
  'duelist_hunter':      "The hook pulled me in range of the riposte.",
  'duelist_warlock':     "The beam couldn't stop the lunge.",
  'duelist_gambler':     "Your wildcard drew a riposte.",

  // NECROMANCER wins
  'necromancer_priest':      "The divine heal met a skeleton. Then a burst.",
  'necromancer_berserker':   "One skeleton is a distraction. Three is a siege.",
  'necromancer_wizard':      "Orbs hit the skeletons. Burst hit you.",
  'necromancer_knight':      "Plate armor doesn't stop an explosion.",
  'necromancer_sapper':      "My mines walk. Yours just sit there.",
  'necromancer_archer':      "Arrows kill skeletons. Bursts kill archers.",
  'necromancer_jester':      "You blinked into the skeleton. Then it burst.",
  'necromancer_cannoneer':   "The skeleton took the shot. Then it burst.",
  'necromancer_duelist':     "Counter on the skeleton. Two more arrived.",
  'necromancer_reaper':      "Even the reaper can be outnumbered.",
  'necromancer_ronin':       "IAI cleaved the skeleton. Burst cleaved you.",
  'necromancer_witch':       "The mark made the burst hit harder. Ironic.",
  'necromancer_hunter':      "The hook pulled a skeleton in. Then it burst.",
  'necromancer_warlock':     "The drain beam found a skeleton. You found a burst.",
  'necromancer_gambler':     "Odds were against you. Also skeletons.",

  // REAPER wins
  'reaper_priest':      "You healed. I healed more.",
  'reaper_berserker':   "Every hit on me healed me. Math was always against you.",
  'reaper_wizard':      "Mana shield halved the damage. Blood harvest doubled the gain.",
  'reaper_knight':      "The plate armor bought time. Not enough.",
  'reaper_sapper':      "The mine healed me. Technically.",
  'reaper_archer':      "Every arrow healed me. Enjoy the quiver.",
  'reaper_jester':      "The dodge eventually runs out of charges.",
  'reaper_cannoneer':   "The cannonball fueled the harvest.",
  'reaper_duelist':     "The counter-thrust was food.",
  'reaper_necromancer': "Your skeletons healed me more than they hurt me.",
  'reaper_ronin':       "The iai hit. I healed half of it back.",
  'reaper_witch':       "The hex made me hit harder. Thank you.",
  'reaper_hunter':      "Hook wounds are food now.",
  'reaper_warlock':     "Leech vs. harvest. The scythe is older.",
  'reaper_gambler':     "Luck runs out. Blood harvest doesn't.",

  // RONIN wins
  'ronin_priest':      "The lightning was fast. The iai was faster.",
  'ronin_berserker':   "You charged into the swing.",
  'ronin_wizard':      "Mana shield absorbed the first slash. Not the second.",
  'ronin_knight':      "The lunge was shorter than the iai.",
  'ronin_sapper':      "Cut through the soot. Blade didn't notice.",
  'ronin_archer':      "Arrows lost to a single stroke.",
  'ronin_jester':      "The blink landed mid-windup. Bad timing.",
  'ronin_cannoneer':   "Your shot took a second. Mine took half.",
  'ronin_duelist':     "Longer reach. Heavier strike.",
  'ronin_necromancer': "The iai cleaved skeletons and necromancer in one pass.",
  'ronin_reaper':      "No harvest if the fight ends in one blow.",
  'ronin_witch':       "The mark landed. So did the iai.",
  'ronin_hunter':      "The hook pulled me into range. That was the mistake.",
  'ronin_warlock':     "The beam needed time to ramp. IAI doesn't ramp.",
  'ronin_gambler':     "You needed luck. I only needed one opening.",

  // WITCH wins
  'witch_priest':      "The blessing didn't break the mark.",
  'witch_berserker':   "The bloodrage hit harder. The mark made it yours.",
  'witch_wizard':      "The hex bounced off the shield and found you anyway.",
  'witch_knight':      "Witch's mark amplified everything. Even sword lunge.",
  'witch_sapper':      "The mine triggered the mark. Then you stepped on another.",
  'witch_archer':      "The hex bolt bounced four times before it found you.",
  'witch_jester':      "You dodged the bolt. Ran into the bounce.",
  'witch_cannoneer':   "Mark applied. Cannon fired. Full damage.",
  'witch_duelist':     "The reflected bolt came back marked.",
  'witch_necromancer': "The skeleton took the mark. Burst hit you at +50%.",
  'witch_reaper':      "Mark applied. Harvest rate: irrelevant.",
  'witch_ronin':       "The iai landed into a mark. You felt that.",
  'witch_hunter':      "The hook pulled you into a hex.",
  'witch_warlock':     "Hex mark vs. drain beam. The mark stacked first.",
  'witch_gambler':     "Your wildcard rolled into a hex. Unlucky.",

  // HUNTER wins
  'hunter_priest':      "Hooked. Stunned. Finished.",
  'hunter_berserker':   "You charged. I hooked. You stopped.",
  'hunter_wizard':      "The orbs can't track what's being reeled in.",
  'hunter_knight':      "The hook found the gap in the plate.",
  'hunter_sapper':      "Hooked you away from your own minefield.",
  'hunter_archer':      "You kite. I reel. Different game.",
  'hunter_jester':      "Hooked mid-blink. Clean catch.",
  'hunter_cannoneer':   "The hook landed before the windup finished.",
  'hunter_duelist':     "Riposte needs range. I removed range.",
  'hunter_necromancer': "Hooked right through the skeleton wall.",
  'hunter_reaper':      "Hooked. Stunned. No harvest window.",
  'hunter_ronin':       "Hooked during the windup. Perfect timing.",
  'hunter_witch':       "The hex marked me. The hook found you.",
  'hunter_warlock':     "The beam can't follow a stun.",
  'hunter_gambler':     "You rolled the dice. I threw the hook.",

  // WARLOCK wins
  'warlock_priest':      "Your healing is linear. My drain accelerates.",
  'warlock_berserker':   "The bloodrage fed the leech beautifully.",
  'warlock_wizard':      "Mana shield doesn't block a beam.",
  'warlock_knight':      "Plate armor is no defense against attrition.",
  'warlock_sapper':      "The wake trail kept you in beam range.",
  'warlock_archer':      "You kept your distance. So did the beam.",
  'warlock_jester':      "Every dodge burned the cooldown. The beam waited.",
  'warlock_cannoneer':   "The windup gave me time to ramp the drain.",
  'warlock_duelist':     "The lunge broke the beam. The beam resumed.",
  'warlock_necromancer': "The skeleton took the beam. You took the next one.",
  'warlock_reaper':      "Your harvest heals damage. Mine prevents it.",
  'warlock_ronin':       "The windup was six seconds of drain.",
  'warlock_witch':       "Two debuffs entered. One drained HP.",
  'warlock_hunter':      "The stun broke the beam. The beam is patient.",
  'warlock_gambler':     "The drain doesn't care what you rolled.",

  // GAMBLER wins
  'gambler_priest':      "God may not gamble. But today luck worked out.",
  'gambler_berserker':   "Rolled max pips. Didn't see that coming.",
  'gambler_wizard':      "The orbs hit every coin. Bounced back. Worth it.",
  'gambler_knight':      "Loaded dice, full pips, maximum coins. Lucky break.",
  'gambler_sapper':      "Hit low pips. The next roll hit max.",
  'gambler_archer':      "Arrows vs. coins. Coins had better odds today.",
  'gambler_jester':      "You dodged the coins. Couldn't dodge the reload.",
  'gambler_cannoneer':   "Both had big cooldowns. Mine paid out.",
  'gambler_duelist':     "Your riposte deflected one coin. I threw six more.",
  'gambler_necromancer': "The skeleton took the coins. The burst fed back into pips.",
  'gambler_reaper':      "Even the reaper can't harvest a coin.",
  'gambler_ronin':       "The iai windup ate three wildcard volleys.",
  'gambler_witch':       "The mark made the coins hit harder. Thanks for the boost.",
  'gambler_hunter':      "The hook was slow. The coins were fast.",
  'gambler_warlock':     "The drain needed time to ramp. The dice were instant.",

  '_default_': "Another day, another fight.",
};
